name: mpr
channels:
  - anaconda
  - intel
  - defaults
dependencies:
  - aiohttp
  - coveralls
  - flake8
  - numpy
  - pandas
  - python=3.8.*
  - pytest
  - pytest-asyncio
  - setuptools
  - wheel
  - pip
  - pip:
    - behave
    - isoweek
