name: mpr
channels:
  - anaconda
  - intel
  - defaults
dependencies:
  - aiohttp
  - coveralls
  - jupyter
  - numpy
  - pandas
  - pytables
  - python=3.7.*
  - seaborn
  - setuptools
  - statsmodels
  - wheel
  - pip
  - pip:
    - behave
